build site:
  image: node:13
  stage: build
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install --progress=false
    - npm run build
    # 当前所有目录打包
    - echo -e "PackDate $(date +"%Y_%m_%d_%H_%M_%S")\nGitCommitSHA ${CI_COMMIT_SHA}" > dist/version.txt
  artifacts:
    expire_in: 1 week
    paths:
      - dist

# unit test:
#   image: node:13
#   stage: test
#   script:
#     - npm config set registry https://registry.npm.taobao.org
#     - npm install --progress=false
#     - npm run test

# 自动部署先注释
# deploy:
#   image: alpine
#   stage: deploy
#   script:
#     - apk add --no-cache rsync openssh
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
#     - chmod 600 ~/.ssh/id_dsa
#     - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#     - rsync -rav --delete dist/ user@server.com:/your/project/path/